name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        py-version: [3.10, 3.11, 3.12]
        exclude:
          - os: macos-14
            py-version: 3.12
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}


# This job should execute on these operating systems - ubuntu-latest, macos-14, windows-latest
# Use os as the key to define these operating systems within the matrix.
# The Set up Python step should install python-version 3.10, 3.11, 3.12
# Use py-version as the key to define these python-version within the matrix.
# Modify the job and step to make use of these matrix values.
# Push and trigger the workflow.
        
# Configure matrix strategy to exclude below combinations:

# os: macos-14
# py-version: 3.12